version: 2.1

gems_persist_key: &gems_persist_key
  key: v0-gems-{{ checksum "Gemfile.lock" }}

workflows:
  review:
    jobs:
      - danger

jobs:
  danger:
    docker:
      - image: circleci/ruby:2.7.2
      - image: 41772ki/swift-mint
    steps:
      - setup_remote_docker
      - run: docker run -it 41772ki/swift-mint mint install realm/SwiftLint@0.40.3
      - checkout
      - run: bundle install
      - run: bundle exec danger
