version: 2.1

gems_persist_key: &gems_persist_key
  key: v0-gems-{{ checksum "Gemfile.lock" }}

workflows:
  review:
    jobs:
      - danger

jobs:
  danger:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec danger
