name: Swift

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Danger
      run: bundle install
    - name: Danger
      run: bundle exec danger
